export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_CLEAR_ITEMS = 'CART_RESET';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const CART_ADD_TO_ITEM = 'CART_ADD_TO_ITEM';
export const CART_ADD_TO_ITEM_FAIL = 'CART_ADD_TO_ITEM_FAIL';

export const GET_USER_CART = 'GET_USER_CART';
export const GET_USER_CART_REQUEST = 'GET_USER_CART_REQUEST';
export const GET_USER_CART_ERROR = 'GET_USER_CART_ERROR';

export const CART_ADD_TO_ITEM_REQUEST = 'CART_ADD_TO_ITEM_REQUEST';
export const CART_ADD_TO_ITEM_SUCCESS = 'CART_ADD_TO_ITEM_SUCCESS';
export const GET_USER_CART_RESET = 'GET_USER_CART_RESET';

export const CART_UPDATE_REQUEST = 'CART_UPDATE_REQUEST';
export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
export const CART_UPDATE_FAIL = 'CART_UPDATE_FAIL';

export const CART_DELETE_ITEM_REQUEST = 'CART_DELETE_ITEM_REQUEST';
export const CART_DELETE_ITEM_SUCCESS = 'CART_DELETE_ITEM_SUCCESS';
export const CART_DELETE_ITEM_FAIL = 'CART_DELETE_ITEM_FAIL';

export const CART_RESET_REQUEST = 'CART_RESET_REQUEST';
export const CART_RESET_SUCCESS = 'CART_RESET_SUCCESS';
export const CART_RESET_FAIL = 'CART_RESET_FAIL';
